# Generated by Django 5.1.5 on 2025-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('position', models.TextField()),
                ('text', models.TextField()),
                ('birthday', models.PositiveSmallIntegerField()),
                ('website', models.URLField()),
                ('phone', models.IntegerField()),
                ('city', models.TextField()),
                ('age', models.IntegerField()),
                ('degree', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('freelencer', models.TextField()),
            ],
        ),
    ]
