# Generated by Django 5.1.5 on 2025-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='freelencer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
