# Generated by Django 5.1.5 on 2025-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_image_alter_about_age_alter_about_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AlterField(
            model_name='about',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='freelencer',
            field=models.TextField(default='Freelance information not available'),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.URLField(default='aviable'),
            preserve_default=False,
        ),
    ]
