# Generated by Django 5.1.5 on 2025-01-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_about_image_alter_about_age_alter_about_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='media/profile_pics/ '),
        ),
    ]
