# Generated by Django 5.1.5 on 2025-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='website',
        ),
        migrations.AddField(
            model_name='about',
            name='profil_image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
