# Generated by Django 5.1.5 on 2025-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_about_website_about_profil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rol1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='rol2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='rol3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
