# Generated by Django 5.1.5 on 2025-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_about_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Poject description')),
                ('image', models.ImageField(upload_to='profile_pics/', verbose_name='Project Image')),
                ('technologies', models.CharField(max_length=200, verbose_name='Texnologies')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub Linki')),
            ],
        ),
    ]
